### ISSUE TITLE
Update alpine docker image to 3.14.1 

### ISSUE THREAD

**Issue by ModestaWis** [xfournet/jready#36]
Hi ! Could you update alpine docker image to 3.14.1 ?  It is security problem with apk-tools with version lower than 2.12.6.

**Comment by xfournet** [comment]
Hi! I just released it. It should fix the security warning
```
❯ docker run --rm -ti xfournet/jready:alpine-3.14.1
/ # cat /etc/alpine-release
3.14.1
/ # apk --version
apk-tools 2.12.7, compiled for x86_64.
````

NB: release is bit more complicated since dockerhub autobuilds have been removed for free accounts  (https://www.docker.com/blog/changes-to-docker-hub-autobuilds/). I need to manually release it now
